services:
  - type: web
    name: whatsapp-rag-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        port: 10000
        sync: false
